# Generated by Django 3.1 on 2020-10-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_personaldetails_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='DOB',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
