# Generated by Django 3.1 on 2020-10-10 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_auto_20201010_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='Date_of_birth',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
